# Generated by Django 3.1.7 on 2021-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=40)),
                ('desc', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_cat', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('pub_date', models.DateField()),
                ('pro_img', models.ImageField(default='', upload_to='shop/images')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
